name: CD - Despliegue a Pages

on:
  workflow_run:
    workflows: ["CI - Pruebas de ejercicios"] # Debe coincidir con el 'name' del primer archivo
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # Solo se ejecuta si el workflow de tests terminó exitosamente!
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Config Pages
        uses: actions/configure-pages@v4
        
      - name: Subir archivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar
        uses: actions/deploy-pages@v4